/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TravelDiariesRouteImport } from './routes/travel-diaries'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StockistsRouteImport } from './routes/stockists'
import { Route as SizingRouteImport } from './routes/sizing'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as FindUsRouteImport } from './routes/find-us'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CareRouteImport } from './routes/care'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as WishlistTokenRouteImport } from './routes/wishlist.$token'
import { Route as UploadsSplatRouteImport } from './routes/uploads/$'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as PayOrderIdRouteImport } from './routes/pay.$orderId'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutResumeRouteImport } from './routes/checkout.resume'
import { Route as CheckoutCancelRouteImport } from './routes/checkout.cancel'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AdminShippingRouteImport } from './routes/admin/shipping'
import { Route as AdminReadinessRouteImport } from './routes/admin/readiness'
import { Route as AdminNewsletterRouteImport } from './routes/admin/newsletter'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminFinanceRouteImport } from './routes/admin/finance'
import { Route as AdminAccountRouteImport } from './routes/admin/account'
import { Route as AdminPromotionsIndexRouteImport } from './routes/admin/promotions/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminPagesIndexRouteImport } from './routes/admin/pages/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin/customers/index'
import { Route as AdminContentIndexRouteImport } from './routes/admin/content/index'
import { Route as AdminCollectionsIndexRouteImport } from './routes/admin/collections/index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog/index'
import { Route as AdminProductsOrderRouteImport } from './routes/admin/products/order'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminProductsSlugRouteImport } from './routes/admin/products/$slug'
import { Route as AdminPagesSlugRouteImport } from './routes/admin/pages/$slug'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin/orders/$orderId'
import { Route as AdminContentSizingRouteImport } from './routes/admin/content/sizing'
import { Route as AdminContentProductMessagesRouteImport } from './routes/admin/content/product-messages'
import { Route as AdminContentNavigationRouteImport } from './routes/admin/content/navigation'
import { Route as AdminContentFooterRouteImport } from './routes/admin/content/footer'
import { Route as AdminContentFindUsRouteImport } from './routes/admin/content/find-us'
import { Route as AdminContentContactRouteImport } from './routes/admin/content/contact'
import { Route as AdminContentCareRouteImport } from './routes/admin/content/care'
import { Route as AdminContentAboutRouteImport } from './routes/admin/content/about'
import { Route as AdminBlogSlugRouteImport } from './routes/admin/blog/$slug'
import { Route as AdminAnalyticsTrafficRouteImport } from './routes/admin/analytics/traffic'
import { Route as AdminAnalyticsProductsRouteImport } from './routes/admin/analytics/products'

const TravelDiariesRoute = TravelDiariesRouteImport.update({
  id: '/travel-diaries',
  path: '/travel-diaries',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StockistsRoute = StockistsRouteImport.update({
  id: '/stockists',
  path: '/stockists',
  getParentRoute: () => rootRouteImport,
} as any)
const SizingRoute = SizingRouteImport.update({
  id: '/sizing',
  path: '/sizing',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const FindUsRoute = FindUsRouteImport.update({
  id: '/find-us',
  path: '/find-us',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRoute = CareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WishlistTokenRoute = WishlistTokenRouteImport.update({
  id: '/wishlist/$token',
  path: '/wishlist/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsSplatRoute = UploadsSplatRouteImport.update({
  id: '/uploads/$',
  path: '/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PayOrderIdRoute = PayOrderIdRouteImport.update({
  id: '/pay/$orderId',
  path: '/pay/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutResumeRoute = CheckoutResumeRouteImport.update({
  id: '/checkout/resume',
  path: '/checkout/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShippingRoute = AdminShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReadinessRoute = AdminReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromotionsIndexRoute = AdminPromotionsIndexRouteImport.update({
  id: '/promotions/',
  path: '/promotions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesIndexRoute = AdminPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentIndexRoute = AdminContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsIndexRoute = AdminCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsOrderRoute = AdminProductsOrderRouteImport.update({
  id: '/products/order',
  path: '/products/order',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsSlugRoute = AdminProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesSlugRoute = AdminPagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentSizingRoute = AdminContentSizingRouteImport.update({
  id: '/content/sizing',
  path: '/content/sizing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentProductMessagesRoute =
  AdminContentProductMessagesRouteImport.update({
    id: '/content/product-messages',
    path: '/content/product-messages',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminContentNavigationRoute = AdminContentNavigationRouteImport.update({
  id: '/content/navigation',
  path: '/content/navigation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentFooterRoute = AdminContentFooterRouteImport.update({
  id: '/content/footer',
  path: '/content/footer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentFindUsRoute = AdminContentFindUsRouteImport.update({
  id: '/content/find-us',
  path: '/content/find-us',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentContactRoute = AdminContentContactRouteImport.update({
  id: '/content/contact',
  path: '/content/contact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentCareRoute = AdminContentCareRouteImport.update({
  id: '/content/care',
  path: '/content/care',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentAboutRoute = AdminContentAboutRouteImport.update({
  id: '/content/about',
  path: '/content/about',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogSlugRoute = AdminBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsTrafficRoute = AdminAnalyticsTrafficRouteImport.update({
  id: '/analytics/traffic',
  path: '/analytics/traffic',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsProductsRoute = AdminAnalyticsProductsRouteImport.update({
  id: '/analytics/products',
  path: '/analytics/products',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/care': typeof CareRoute
  '/cart': typeof CartRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/find-us': typeof FindUsRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/sizing': typeof SizingRoute
  '/stockists': typeof StockistsRoute
  '/terms': typeof TermsRoute
  '/travel-diaries': typeof TravelDiariesRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/readiness': typeof AdminReadinessRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/api/$': typeof ApiSplatRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/resume': typeof CheckoutResumeRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/pay/$orderId': typeof PayOrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/wishlist/$token': typeof WishlistTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/analytics/products': typeof AdminAnalyticsProductsRoute
  '/admin/analytics/traffic': typeof AdminAnalyticsTrafficRoute
  '/admin/blog/$slug': typeof AdminBlogSlugRoute
  '/admin/content/about': typeof AdminContentAboutRoute
  '/admin/content/care': typeof AdminContentCareRoute
  '/admin/content/contact': typeof AdminContentContactRoute
  '/admin/content/find-us': typeof AdminContentFindUsRoute
  '/admin/content/footer': typeof AdminContentFooterRoute
  '/admin/content/navigation': typeof AdminContentNavigationRoute
  '/admin/content/product-messages': typeof AdminContentProductMessagesRoute
  '/admin/content/sizing': typeof AdminContentSizingRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/pages/$slug': typeof AdminPagesSlugRoute
  '/admin/products/$slug': typeof AdminProductsSlugRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products/order': typeof AdminProductsOrderRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/collections/': typeof AdminCollectionsIndexRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/promotions/': typeof AdminPromotionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/care': typeof CareRoute
  '/cart': typeof CartRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/find-us': typeof FindUsRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/sizing': typeof SizingRoute
  '/stockists': typeof StockistsRoute
  '/terms': typeof TermsRoute
  '/travel-diaries': typeof TravelDiariesRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/readiness': typeof AdminReadinessRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/api/$': typeof ApiSplatRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/resume': typeof CheckoutResumeRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/pay/$orderId': typeof PayOrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/wishlist/$token': typeof WishlistTokenRoute
  '/admin': typeof AdminIndexRoute
  '/admin/analytics/products': typeof AdminAnalyticsProductsRoute
  '/admin/analytics/traffic': typeof AdminAnalyticsTrafficRoute
  '/admin/blog/$slug': typeof AdminBlogSlugRoute
  '/admin/content/about': typeof AdminContentAboutRoute
  '/admin/content/care': typeof AdminContentCareRoute
  '/admin/content/contact': typeof AdminContentContactRoute
  '/admin/content/find-us': typeof AdminContentFindUsRoute
  '/admin/content/footer': typeof AdminContentFooterRoute
  '/admin/content/navigation': typeof AdminContentNavigationRoute
  '/admin/content/product-messages': typeof AdminContentProductMessagesRoute
  '/admin/content/sizing': typeof AdminContentSizingRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/pages/$slug': typeof AdminPagesSlugRoute
  '/admin/products/$slug': typeof AdminProductsSlugRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products/order': typeof AdminProductsOrderRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/collections': typeof AdminCollectionsIndexRoute
  '/admin/content': typeof AdminContentIndexRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/pages': typeof AdminPagesIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/promotions': typeof AdminPromotionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/care': typeof CareRoute
  '/cart': typeof CartRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/find-us': typeof FindUsRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/sizing': typeof SizingRoute
  '/stockists': typeof StockistsRoute
  '/terms': typeof TermsRoute
  '/travel-diaries': typeof TravelDiariesRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/readiness': typeof AdminReadinessRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/api/$': typeof ApiSplatRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/resume': typeof CheckoutResumeRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/pay/$orderId': typeof PayOrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/wishlist/$token': typeof WishlistTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/analytics/products': typeof AdminAnalyticsProductsRoute
  '/admin/analytics/traffic': typeof AdminAnalyticsTrafficRoute
  '/admin/blog/$slug': typeof AdminBlogSlugRoute
  '/admin/content/about': typeof AdminContentAboutRoute
  '/admin/content/care': typeof AdminContentCareRoute
  '/admin/content/contact': typeof AdminContentContactRoute
  '/admin/content/find-us': typeof AdminContentFindUsRoute
  '/admin/content/footer': typeof AdminContentFooterRoute
  '/admin/content/navigation': typeof AdminContentNavigationRoute
  '/admin/content/product-messages': typeof AdminContentProductMessagesRoute
  '/admin/content/sizing': typeof AdminContentSizingRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/pages/$slug': typeof AdminPagesSlugRoute
  '/admin/products/$slug': typeof AdminProductsSlugRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products/order': typeof AdminProductsOrderRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/collections/': typeof AdminCollectionsIndexRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/promotions/': typeof AdminPromotionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/care'
    | '/cart'
    | '/collection'
    | '/contact'
    | '/faq'
    | '/find-us'
    | '/returns'
    | '/shipping'
    | '/sizing'
    | '/stockists'
    | '/terms'
    | '/travel-diaries'
    | '/admin/account'
    | '/admin/finance'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/newsletter'
    | '/admin/readiness'
    | '/admin/shipping'
    | '/api/$'
    | '/checkout/cancel'
    | '/checkout/resume'
    | '/checkout/success'
    | '/journal/$slug'
    | '/pay/$orderId'
    | '/product/$slug'
    | '/uploads/$'
    | '/wishlist/$token'
    | '/admin/'
    | '/admin/analytics/products'
    | '/admin/analytics/traffic'
    | '/admin/blog/$slug'
    | '/admin/content/about'
    | '/admin/content/care'
    | '/admin/content/contact'
    | '/admin/content/find-us'
    | '/admin/content/footer'
    | '/admin/content/navigation'
    | '/admin/content/product-messages'
    | '/admin/content/sizing'
    | '/admin/orders/$orderId'
    | '/admin/pages/$slug'
    | '/admin/products/$slug'
    | '/admin/products/new'
    | '/admin/products/order'
    | '/admin/blog/'
    | '/admin/collections/'
    | '/admin/content/'
    | '/admin/customers/'
    | '/admin/orders/'
    | '/admin/pages/'
    | '/admin/products/'
    | '/admin/promotions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/care'
    | '/cart'
    | '/collection'
    | '/contact'
    | '/faq'
    | '/find-us'
    | '/returns'
    | '/shipping'
    | '/sizing'
    | '/stockists'
    | '/terms'
    | '/travel-diaries'
    | '/admin/account'
    | '/admin/finance'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/newsletter'
    | '/admin/readiness'
    | '/admin/shipping'
    | '/api/$'
    | '/checkout/cancel'
    | '/checkout/resume'
    | '/checkout/success'
    | '/journal/$slug'
    | '/pay/$orderId'
    | '/product/$slug'
    | '/uploads/$'
    | '/wishlist/$token'
    | '/admin'
    | '/admin/analytics/products'
    | '/admin/analytics/traffic'
    | '/admin/blog/$slug'
    | '/admin/content/about'
    | '/admin/content/care'
    | '/admin/content/contact'
    | '/admin/content/find-us'
    | '/admin/content/footer'
    | '/admin/content/navigation'
    | '/admin/content/product-messages'
    | '/admin/content/sizing'
    | '/admin/orders/$orderId'
    | '/admin/pages/$slug'
    | '/admin/products/$slug'
    | '/admin/products/new'
    | '/admin/products/order'
    | '/admin/blog'
    | '/admin/collections'
    | '/admin/content'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/promotions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/care'
    | '/cart'
    | '/collection'
    | '/contact'
    | '/faq'
    | '/find-us'
    | '/returns'
    | '/shipping'
    | '/sizing'
    | '/stockists'
    | '/terms'
    | '/travel-diaries'
    | '/admin/account'
    | '/admin/finance'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/newsletter'
    | '/admin/readiness'
    | '/admin/shipping'
    | '/api/$'
    | '/checkout/cancel'
    | '/checkout/resume'
    | '/checkout/success'
    | '/journal/$slug'
    | '/pay/$orderId'
    | '/product/$slug'
    | '/uploads/$'
    | '/wishlist/$token'
    | '/admin/'
    | '/admin/analytics/products'
    | '/admin/analytics/traffic'
    | '/admin/blog/$slug'
    | '/admin/content/about'
    | '/admin/content/care'
    | '/admin/content/contact'
    | '/admin/content/find-us'
    | '/admin/content/footer'
    | '/admin/content/navigation'
    | '/admin/content/product-messages'
    | '/admin/content/sizing'
    | '/admin/orders/$orderId'
    | '/admin/pages/$slug'
    | '/admin/products/$slug'
    | '/admin/products/new'
    | '/admin/products/order'
    | '/admin/blog/'
    | '/admin/collections/'
    | '/admin/content/'
    | '/admin/customers/'
    | '/admin/orders/'
    | '/admin/pages/'
    | '/admin/products/'
    | '/admin/promotions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  CareRoute: typeof CareRoute
  CartRoute: typeof CartRoute
  CollectionRoute: typeof CollectionRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FindUsRoute: typeof FindUsRoute
  ReturnsRoute: typeof ReturnsRoute
  ShippingRoute: typeof ShippingRoute
  SizingRoute: typeof SizingRoute
  StockistsRoute: typeof StockistsRoute
  TermsRoute: typeof TermsRoute
  TravelDiariesRoute: typeof TravelDiariesRoute
  ApiSplatRoute: typeof ApiSplatRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutResumeRoute: typeof CheckoutResumeRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  JournalSlugRoute: typeof JournalSlugRoute
  PayOrderIdRoute: typeof PayOrderIdRoute
  ProductSlugRoute: typeof ProductSlugRoute
  UploadsSplatRoute: typeof UploadsSplatRoute
  WishlistTokenRoute: typeof WishlistTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/travel-diaries': {
      id: '/travel-diaries'
      path: '/travel-diaries'
      fullPath: '/travel-diaries'
      preLoaderRoute: typeof TravelDiariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stockists': {
      id: '/stockists'
      path: '/stockists'
      fullPath: '/stockists'
      preLoaderRoute: typeof StockistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sizing': {
      id: '/sizing'
      path: '/sizing'
      fullPath: '/sizing'
      preLoaderRoute: typeof SizingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-us': {
      id: '/find-us'
      path: '/find-us'
      fullPath: '/find-us'
      preLoaderRoute: typeof FindUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/wishlist/$token': {
      id: '/wishlist/$token'
      path: '/wishlist/$token'
      fullPath: '/wishlist/$token'
      preLoaderRoute: typeof WishlistTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads/$': {
      id: '/uploads/$'
      path: '/uploads/$'
      fullPath: '/uploads/$'
      preLoaderRoute: typeof UploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$orderId': {
      id: '/pay/$orderId'
      path: '/pay/$orderId'
      fullPath: '/pay/$orderId'
      preLoaderRoute: typeof PayOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/resume': {
      id: '/checkout/resume'
      path: '/checkout/resume'
      fullPath: '/checkout/resume'
      preLoaderRoute: typeof CheckoutResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shipping': {
      id: '/admin/shipping'
      path: '/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AdminShippingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/readiness': {
      id: '/admin/readiness'
      path: '/readiness'
      fullPath: '/admin/readiness'
      preLoaderRoute: typeof AdminReadinessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotions/': {
      id: '/admin/promotions/'
      path: '/promotions'
      fullPath: '/admin/promotions/'
      preLoaderRoute: typeof AdminPromotionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages/': {
      id: '/admin/pages/'
      path: '/pages'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AdminPagesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/': {
      id: '/admin/content/'
      path: '/content'
      fullPath: '/admin/content/'
      preLoaderRoute: typeof AdminContentIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections/': {
      id: '/admin/collections/'
      path: '/collections'
      fullPath: '/admin/collections/'
      preLoaderRoute: typeof AdminCollectionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/order': {
      id: '/admin/products/order'
      path: '/products/order'
      fullPath: '/admin/products/order'
      preLoaderRoute: typeof AdminProductsOrderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/$slug': {
      id: '/admin/products/$slug'
      path: '/products/$slug'
      fullPath: '/admin/products/$slug'
      preLoaderRoute: typeof AdminProductsSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages/$slug': {
      id: '/admin/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/admin/pages/$slug'
      preLoaderRoute: typeof AdminPagesSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/sizing': {
      id: '/admin/content/sizing'
      path: '/content/sizing'
      fullPath: '/admin/content/sizing'
      preLoaderRoute: typeof AdminContentSizingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/product-messages': {
      id: '/admin/content/product-messages'
      path: '/content/product-messages'
      fullPath: '/admin/content/product-messages'
      preLoaderRoute: typeof AdminContentProductMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/navigation': {
      id: '/admin/content/navigation'
      path: '/content/navigation'
      fullPath: '/admin/content/navigation'
      preLoaderRoute: typeof AdminContentNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/footer': {
      id: '/admin/content/footer'
      path: '/content/footer'
      fullPath: '/admin/content/footer'
      preLoaderRoute: typeof AdminContentFooterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/find-us': {
      id: '/admin/content/find-us'
      path: '/content/find-us'
      fullPath: '/admin/content/find-us'
      preLoaderRoute: typeof AdminContentFindUsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/contact': {
      id: '/admin/content/contact'
      path: '/content/contact'
      fullPath: '/admin/content/contact'
      preLoaderRoute: typeof AdminContentContactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/care': {
      id: '/admin/content/care'
      path: '/content/care'
      fullPath: '/admin/content/care'
      preLoaderRoute: typeof AdminContentCareRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/about': {
      id: '/admin/content/about'
      path: '/content/about'
      fullPath: '/admin/content/about'
      preLoaderRoute: typeof AdminContentAboutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/$slug': {
      id: '/admin/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/admin/blog/$slug'
      preLoaderRoute: typeof AdminBlogSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics/traffic': {
      id: '/admin/analytics/traffic'
      path: '/analytics/traffic'
      fullPath: '/admin/analytics/traffic'
      preLoaderRoute: typeof AdminAnalyticsTrafficRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics/products': {
      id: '/admin/analytics/products'
      path: '/analytics/products'
      fullPath: '/admin/analytics/products'
      preLoaderRoute: typeof AdminAnalyticsProductsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccountRoute: typeof AdminAccountRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminReadinessRoute: typeof AdminReadinessRoute
  AdminShippingRoute: typeof AdminShippingRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAnalyticsProductsRoute: typeof AdminAnalyticsProductsRoute
  AdminAnalyticsTrafficRoute: typeof AdminAnalyticsTrafficRoute
  AdminBlogSlugRoute: typeof AdminBlogSlugRoute
  AdminContentAboutRoute: typeof AdminContentAboutRoute
  AdminContentCareRoute: typeof AdminContentCareRoute
  AdminContentContactRoute: typeof AdminContentContactRoute
  AdminContentFindUsRoute: typeof AdminContentFindUsRoute
  AdminContentFooterRoute: typeof AdminContentFooterRoute
  AdminContentNavigationRoute: typeof AdminContentNavigationRoute
  AdminContentProductMessagesRoute: typeof AdminContentProductMessagesRoute
  AdminContentSizingRoute: typeof AdminContentSizingRoute
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
  AdminPagesSlugRoute: typeof AdminPagesSlugRoute
  AdminProductsSlugRoute: typeof AdminProductsSlugRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsOrderRoute: typeof AdminProductsOrderRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminCollectionsIndexRoute: typeof AdminCollectionsIndexRoute
  AdminContentIndexRoute: typeof AdminContentIndexRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminPagesIndexRoute: typeof AdminPagesIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminPromotionsIndexRoute: typeof AdminPromotionsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountRoute: AdminAccountRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminReadinessRoute: AdminReadinessRoute,
  AdminShippingRoute: AdminShippingRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAnalyticsProductsRoute: AdminAnalyticsProductsRoute,
  AdminAnalyticsTrafficRoute: AdminAnalyticsTrafficRoute,
  AdminBlogSlugRoute: AdminBlogSlugRoute,
  AdminContentAboutRoute: AdminContentAboutRoute,
  AdminContentCareRoute: AdminContentCareRoute,
  AdminContentContactRoute: AdminContentContactRoute,
  AdminContentFindUsRoute: AdminContentFindUsRoute,
  AdminContentFooterRoute: AdminContentFooterRoute,
  AdminContentNavigationRoute: AdminContentNavigationRoute,
  AdminContentProductMessagesRoute: AdminContentProductMessagesRoute,
  AdminContentSizingRoute: AdminContentSizingRoute,
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
  AdminPagesSlugRoute: AdminPagesSlugRoute,
  AdminProductsSlugRoute: AdminProductsSlugRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsOrderRoute: AdminProductsOrderRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminCollectionsIndexRoute: AdminCollectionsIndexRoute,
  AdminContentIndexRoute: AdminContentIndexRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminPagesIndexRoute: AdminPagesIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminPromotionsIndexRoute: AdminPromotionsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  CareRoute: CareRoute,
  CartRoute: CartRoute,
  CollectionRoute: CollectionRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FindUsRoute: FindUsRoute,
  ReturnsRoute: ReturnsRoute,
  ShippingRoute: ShippingRoute,
  SizingRoute: SizingRoute,
  StockistsRoute: StockistsRoute,
  TermsRoute: TermsRoute,
  TravelDiariesRoute: TravelDiariesRoute,
  ApiSplatRoute: ApiSplatRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutResumeRoute: CheckoutResumeRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  JournalSlugRoute: JournalSlugRoute,
  PayOrderIdRoute: PayOrderIdRoute,
  ProductSlugRoute: ProductSlugRoute,
  UploadsSplatRoute: UploadsSplatRoute,
  WishlistTokenRoute: WishlistTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
